# Source: inferencepool/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vllm-llama3-8b-instruct-epp
  labels:
    app.kubernetes.io/name: vllm-llama3-8b-instruct-epp
    app.kubernetes.io/version: "v1.1.0"
